export const mockedPosts = [
  {
    id: 1,
    title: "First Post",
    content: "Hello World",
    vote: 8,
    voteAction: null,
    comments: [],
    createdAt: 1780413500218,
  },
  {
    id: 2,
    title: "Second Post",
    content: "JS Warm Up",
    vote: 0,
    voteAction: null,
    comments: [],
    createdAt: 1780413500218,
  },
  {
    id: 3,
    title: "Third Post",
    content: "Array & Objects",
    vote: 2,
    voteAction: null,
    comments: [],
    createdAt: 1780413500218,
  },
  {
    id: 4,
    title: "Fourth Post",
    content: "Add Incomplete",
    vote: 5,
    voteAction: null,
    comments: [],
    createdAt: 1780413500218,
  },
  {
    id: 5,
    title: "Fifth Post",
    content: "Filter Incomplete",
    vote: 11,
    voteAction: null,
    comments: [],
    createdAt: 1780413500218,
  },
  {
    id: 6,
    title: "Sixth Post",
    content: "All Is Well",
    vote: 33,
    voteAction: null,
    comments: [],
    createdAt: 1780413500218,
  },
];
